### ISSUE TITLE
Docker Deploy Error Permission denied: 'data'

### ISSUE THREAD

**Issue by Genry777Morgan** [yshalsager/telegram-feedback-bot#25]
```
 ✔ Container feedbackbot  Recreated                                                                                                                                    0.0s
Attaching to feedbackbot
feedbackbot  | Traceback (most recent call last):
feedbackbot  |   File "/code/.venv/bin/alembic", line 8, in <module>
feedbackbot  |     sys.exit(main())
feedbackbot  |              ^^^^^^
feedbackbot  |   File "/code/.venv/lib/python3.12/site-packages/alembic/config.py", line 636, in main
feedbackbot  |     CommandLine(prog=prog).main(argv=argv)
feedbackbot  |   File "/code/.venv/lib/python3.12/site-packages/alembic/config.py", line 626, in main
feedbackbot  |     self.run_cmd(cfg, options)
feedbackbot  |   File "/code/.venv/lib/python3.12/site-packages/alembic/config.py", line 603, in run_cmd
feedbackbot  |     fn(
feedbackbot  |   File "/code/.venv/lib/python3.12/site-packages/alembic/command.py", line 406, in upgrade
feedbackbot  |     script.run_env()
feedbackbot  |   File "/code/.venv/lib/python3.12/site-packages/alembic/script/base.py", line 582, in run_env
feedbackbot  |     util.load_python_file(self.dir, "env.py")
feedbackbot  |   File "/code/.venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
feedbackbot  |     module = load_module_py(module_id, path)
feedbackbot  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
feedbackbot  |   File "/code/.venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
feedbackbot  |     spec.loader.exec_module(module)  # type: ignore
feedbackbot  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
feedbackbot  |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
feedbackbot  |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
feedbackbot  |   File "/code/app/src/builder/db/migrations/env.py", line 6, in <module>
feedbackbot  |     from src.builder.db.base import Base
feedbackbot  |   File "/code/app/src/__init__.py", line 14, in <module>
feedbackbot  |     DATA_DIR.mkdir(parents=True, exist_ok=True)
feedbackbot  |   File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
feedbackbot  |     os.mkdir(self, mode)
feedbackbot  | PermissionError: [Errno 13] Permission denied: 'data'
feedbackbot exited with code 0
```

**Comment by yshalsager** [comment]
Can you create data directory from outside of docker and see?

**Comment by Genry777Morgan** [comment]
feedbackbot  |   File "/code/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 621, in connect
feedbackbot  |     return self.loaded_dbapi.connect(*cargs, **cparams)
feedbackbot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
feedbackbot  | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
feedbackbot  | (Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by Genry777Morgan** [comment]
> Can you create data directory from outside of docker and see?
feedbackbot | File "/code/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 621, in connect
feedbackbot | return self.loaded_dbapi.connect(*cargs, **cparams)
feedbackbot | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
feedbackbot | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
feedbackbot | (Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by Genry777Morgan** [comment]
@yshalsager

**Comment by yshalsager** [comment]
@Genry777Morgan I have started the container in a directory that doesn't have data folder yet, and it got created without problems here.
